services:
  - type: web
    region: ohio
    name: sample-service-name
    env: python
    plan: free
    numInstances: 1
    
    # Build command CORREGIDO:
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      npm install && npm run build
      
    # Start command CORREGIDO:
    startCommand: "gunicorn src.wsgi:app --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        value: "any-key-works-for-development"
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: NODE_VERSION
        value: 20.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: []
    plan: free